export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_USER = 'CHANGE_USER';
export const CHANGE_LOCATION = 'CHANGE_LOCATION';
export const CHANGE_HUNT_METHOD = 'CHANGE_HUNT_METHOD';
export const CHANGE_OLD_PASSWORD = 'CHANGE_OLD_PASSWORD';
export const CHANGE_NEW_PASSWORD_1 = 'CHANGE_NEW_PASSWORD_1';
export const CHANGE_NEW_PASSWORD_2 = 'CHANGE_NEW_PASSWORD_2';

export const CHANGE_NAME = 'CHANGE_NAME';
export const CHANGE_ROUTE = 'CHANGE_ROUTE';
export const CHANGE_ISSIGNIN = 'CHANGE_ISSIGNIN';

export const CHANGE_ANOTHER_BOOK_DATA = 'CHANGE_ANOTHER_BOOK_DATA';

export const UPDATE_TABLE = 'UPDATE_TABLE';
export const UPDATE_TABLE_MY_BOOK = 'UPDATE_TABLE_MY_BOOK';
export const UPDATE_INPUT_FORM = 'UPDATE_INPUT_FORM';
export const RELOAD_INPUT_FORM = 'RELOAD_INPUT_FORM';

export const DB_DATE = 'DB_DATE';
export const DB_TIME = 'DB_TIME';
export const DB_NAME = 'DB_NAME';
export const DB_LOCATION = 'DB_LOCATION';
export const DB_HUNT_METHOD = 'DB_HUNT_METHOD';
export const DB_LAST_INSERT_TO_BOOK = 'DB_LAST_INSERT_TO_BOOK';
export const DB_GUEST_NAME = 'DB_GUEST_NAME';

export const CHANGE_PROFILE_OPEN = 'CHANGE_PROFILE_OPEN';
export const CHANGE_RASSWORD_OPEN = 'CHANGE_RASSWORD_OPEN';
export const CHANGE_ANOTHER_BOOK_INFO_OPEN = 'CHANGE_ANOTHER_BOOK_INFO_OPEN';
export const MY_BOOK_OPEN = 'MY_BOOK_OPEN';
export const UPDATE_ANNOUNCEMENTS = 'UPDATE_ANNOUNCEMENTS';

export const IS_PASSWORD_CHANGE = 'IS_PASSWORD_CHANGE';

export const SET_LEAVE_TIME = 'SET_LEAVE_TIME';
export const SET_LEAVE_COUNT = 'SET_VALUE_COUNT';
export const SET_LEAVE_SPECIES_GENDER = 'SET_LEAVE_SPECIES_GENDER';
export const SET_LEAVE_TIME_LOCATION = 'SET_LEAVE_TIME_LOCATION';
export const SET_LEAVE_U_N = 'SET_LEAVE_U_N';
export const SET_LEAVE_TAG_NUMBER = 'SET_LEAVE_TAG_NUMBER';
export const SET_LEAVE_OTHER = 'SET_LEAVE_OTHER';

export const DOWNLOAD_FILE_NAME = 'DOWNLOAD_FILE_NAME';

export const NUMBER_OF_DATA_IN_BOOK_TABLE = 'NUMBER_OF_DATA_IN_BOOK_TABLE';
export const NUMBER_OF_DATA_IN_ANNOUNCEMENTS_TABLE = 'NUMBER_OF_DATA_IN_ANNOUNCEMENTS_TABLE';
export const NUMBER_OF_DATA_IN_MY_BOOK_TABLE = 'NUMBER_OF_DATA_IN_MY_BOOK_TABLE';
export const NUMBER_OF_VISUALIZE_DATA = 'NUMBER_OF_VISUALIZE_DATA';
export const NUMBER_OFFSET_TABLE_BOOK = 'NUMBER_OFFSET_TABLE_BOOK';
export const NUMBER_OFFSET_TABLE_ANNOUNCEMENTS = 'NUMBER_OFFSET_TABLE_ANNOUNCEMENTS';
export const NUMBER_OFFSET_TABLE_MYBOOK = 'NUMBER_OFFSET_TABLE_MYBOOK';

export const REGISTER_NAME_PZ = 'REGISTER_NAME_PZ';
export const REGISTER_NUMBER_OF_MEMBERS = 'REGISTER_NUMBER_OF_MEMBERS';
export const REGISTER_MEMBERS = 'REGISTER_MEMBERS';
export const REGISTRATION_OPEN_EDIT_MEMBER = 'REGISTRATION_OPEN_EDIT_MEMBER';


